Etch/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Etch.Models;
using Etch.Models.ScheduleModels;
using System.IO;
using System.Threading;
using System.Globalization;
using Etch.Data;

namespace Etch.Controllers {
    [Authorize]
    [Route("[controller]/[action]")]
    public class ScheduleController : Controller {
        private readonly ITasksRepository tasksRepository;
        private readonly IRequestUser requestUser;

        /// <summary>
        /// Constructor method used to initialize new schedule object instance.
        /// </summary>
        /// <param name="tasksRepository">Tasks repository object.</param>
        /// <param name="requestUser">Request user object.</param>
        public ScheduleController(ITasksRepository tasksRepository, IRequestUser requestUser) {
            this.tasksRepository = tasksRepository;
            this.requestUser = requestUser;
        }

        /// <summary>
        /// Method used to return schedule index view.
        /// </summary>
        /// <returns>Schedule index view.</returns>
        [HttpGet]
        public async Task<IActionResult> Index() {
            return View(await tasksRepository.GetAll());
        }

        /// <summary>
        /// Method used to return partial view containing details corresponding to passed in Id.
        /// </summary>
        /// <param name="id">String Id of task to determine.</param>
        /// <returns>Details partial view.</returns>
        public async Task<IActionResult> Details(string id) {
            if (String.IsNullOrEmpty(id))
                return NotFound();

            var task = await tasksRepository.Find(id);
            if (task == null)
                return NotFound();

            return PartialView("_Details", task);
        }

        /// <summary>
        /// Method used to return add task view.
        /// </summary>
        /// <returns>Add task view.</returns>
        [Authorize]
        public IActionResult AddTask() {
            return View();
        }

        /// <summary>
        /// Method used to return add task view containing status message of result.
        /// </summary>
        /// <param name="model">Gantt task model containing task information.</param>
        /// <returns>Redirect to schedule index view or add task view if failed.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> AddTask(GanttTask task) {
            if (ModelState.IsValid) {
                task.UserId = requestUser.GetUserId();
                tasksRepository.Add(task);
                await tasksRepository.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(task);
        }

        /// <summary>
        /// Method used to update existing task.
        /// </summary>
        /// <param name="model">Gantt task model containing updated task information.</param>
        /// <returns>Redirect to schedule index view or index if failed.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Update(GanttTask task) {
            if (ModelState.IsValid) {
                task.UserId = requestUser.GetUserId();
                tasksRepository.Update(task);
                await tasksRepository.SaveChanges();
                return RedirectToAction("Index");
            }
            return PartialView(task);
        }

        /// <summary>
        /// method used to delete task from repository.
        /// </summary>
        /// <param name="id">Task Id.</param>
        /// <returns>Returns current view without task.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Delete(string id) {
            if (String.IsNullOrEmpty(id))
                return NotFound();

            var task = await tasksRepository.Find(id);
            if (task == null)
                return NotFound();

            tasksRepository.Remove(task);
            await tasksRepository.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Etch/Controllers/SharedController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Etch.Models;
using System.IO;

namespace Etch.Controllers {
    [Authorize]
    [Route("[controller]/[action]")]
    public class SharedController : Controller {
        private readonly UserManager<ApplicationUser> userManager;

        /// <summary>
        /// Shared controller constructor method.
        /// </summary>
        public SharedController(UserManager<ApplicationUser> userManager) {
            this.userManager = userManager;
        }

        /// <summary>
        /// Method used to get users profile photo if it exists or a default one if not.
        /// </summary>
        /// <returns>Returns the contents of the binary file to the response.</returns>
        public async Task<FileContentResult> ProfilePhoto() {
            var user = await userManager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{userManager.GetUserId(User)}'.");

            // If user doesnt have a set profile photo
            if (user.ProfilePhoto.Length < 1) {
                // Get default profile image
                var defaultFile = Path.Combine("~/assets/images/content/profile/default.png");
                var request = HttpContext.Request;
                var uriBuilder = new UriBuilder {
                    Host = request.Host.Host,
                    Scheme = request.Scheme
                };
                if (request.Host.Port.HasValue)
                    uriBuilder.Port = request.Host.Port.Value;

                // Convert default image into byte array
                FileInfo fileInfo = new FileInfo(uriBuilder.ToString());
                long imageFileLength = fileInfo.Length;
                FileStream stream = new FileStream(defaultFile, FileMode.Open, FileAccess.Read);
                BinaryReader reader = new BinaryReader(stream);
                byte[] profileData = reader.ReadBytes((int)imageFileLength);

                // Return default image
                return new FileContentResult(profileData, "image/png");
            }

            // Return profile photo image
            return new FileContentResult(user.ProfilePhoto, "image/jpeg");
        }

        /// <summary>
        /// Method used to change the users current theme.
        /// </summary>
        /// <param name="submit">String type of new selected theme to change to.</param>
        /// <returns>Redirect to dashboard view.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeTheme(string submit) {
            var user = await userManager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{userManager.GetUserId(User)}'.");

            // Update theme
            user.Theme = submit;
            await userManager.UpdateAsync(user);

            // Redirect to dashboard
            return RedirectToAction(nameof(DashboardController.Index), "Dashboard");
        }
    }
}

Etch/ViewComponents/ThemeViewComponent.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Etch.Models;

namespace Etch.Controllers {
    public class ThemeViewComponent : ViewComponent {
        private readonly UserManager<ApplicationUser> userManager;

        /// <summary>
        /// Background controller constructor method.
        /// </summary>
        public ThemeViewComponent(UserManager<ApplicationUser> userManager) {
            this.userManager = userManager;
        }

        /// <summary>
        /// Method used to get the current users selected background colour.
        /// </summary>
        /// <returns>Returns theme model containing theme model of current signed in user.</returns>
        public async Task<IViewComponentResult> InvokeAsync() {
            var user = await userManager.GetUserAsync(HttpContext.User);
            
            // Create model with default theme
            ThemeModel model = new ThemeModel { Theme = ApplicationUser.Themes.Default };

            // If user exists set theme
            if (user != null)
                model.Theme = user.ThemeEnum;

            // Return background view containing model
            return View("~/Views/Shared/_Theme.cshtml", model);
        }
    }
}

Etch/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="banner float-right">
    @if (SignInManager.IsSignedIn(User)) {
        <!-- Navigation Icons -->
        <a asp-area="" asp-controller="Schedule" asp-action="AddTask" class="icon transition-4s"><img src="~/assets/images/header/plus.png" alt="Add" /></a>
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            @Html.AntiForgeryToken()
            <button type="submit" class="clear-button-styling icon transition-4s"><img src="~/assets/images/header/logout.png" alt="Logout" /></button>
        </form>
        <a asp-area="" asp-controller="Manage" asp-action="Index" class="icon transition-4s"><img src="~/assets/images/header/settings.png" alt="Settings" /></a>
    } else { 
        <a asp-area="" asp-controller="Account" asp-action="Login" class="nav-link transition-2s">Login</a>
        <a asp-area="" asp-controller="Account" asp-action="Register" class="nav-link transition-2s">Register</a>
    }

    <!-- Logo -->
    <a asp-area="" asp-controller="Home" asp-action="Index" class="logo transition-4s"><img src="~/assets/images/header/etch.png" alt="Logo" /></a>
</div>
<div class="banner float-left transition-4s" id="sidebar-push">
    @if (SignInManager.IsSignedIn(User)) {
        <h2>@ViewData["Title"]</h2>
    }
</div>

@if (SignInManager.IsSignedIn(User)) {
    <div id="sidebar">
        <ul id="sidebar-menu" class="transition-4s">
            <div class="sidebar-title">
                <img id="menu-icon" src="~/assets/images/header/nav/menu.png" alt="Menu" class="transition-2s" href="#" onclick="openNav()">
            </div>
            <li>
                <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="@(ViewData["Title"].Equals("Dashboard") ? "active" : "") transition-4s">
                    <img src="~/assets/images/header/nav/home.png" alt="Icon">
                    <span>Dashboard</span>
                    <img src="~/assets/images/header/nav/arrow.png">
                </a>
            </li>
            <li>
                <a asp-area="" asp-controller="Schedule" asp-action="Index" class="@(ViewData["Title"].Equals("Schedule") ? "active" : "") transition-4s">
                    <img src="~/assets/images/header/nav/schedule.png" alt="Icon">
                    <span>Schedule</span>
                    <img src="~/assets/images/header/nav/arrow.png">
                </a>
            </li>
            <li>
                <a href="#" class="@(ViewData["Title"].Equals("Goals") ? "active" : "") transition-4s">
                    <img src="~/assets/images/header/nav/goals.png" alt="Icon">
                    <span>Goals</span>
                    <img src="~/assets/images/header/nav/arrow.png">
                </a>
            </li>
            <li>
                <a href="#" class="@(ViewData["Title"].Equals("Notes") ? "active" : "") transition-4s">
                    <img src="~/assets/images/header/nav/notes.png" alt="Icon">
                    <span>Notes</span>
                    <img src="~/assets/images/header/nav/arrow.png">
                </a>
            </li>
            <li>
                <a asp-area="" asp-controller="Manage" asp-action="Index" class="@(ViewData["Title"].Equals("Profile") ? "active" : "") transition-4s">
                    <img src="~/assets/images/header/nav/settings.png" alt="Icon">
                    <span>Profile</span>
                    <img src="~/assets/images/header/nav/arrow.png">
                </a>
            </li>
            <div class="sidebar-profile">
                <div class="profile" style="background-image: url('@Url.Action("ProfilePhoto", "Shared")') !important"></div>
                <div>User</div>
                <div>@UserManager.GetUserAsync(User).Result.FirstName @UserManager.GetUserAsync(User).Result.LastName</div>
            </div>
        </ul>
    </div>

    <!-- Theme Picker -->
    <div id="theme-picker" class="transition-4s">
        <div class="toggle"><img src="~/assets/images/content/profile/color-wheel.png" alt="Theme Picker" /> </div>
        <h3>Theme Picker</h3>
        <p>Personalise your experience with one of the following themes!</p>
        <form asp-controller="Shared" asp-action="ChangeTheme"  asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
            <button type="submit" name="submit" value="Default">
                <div></div>
                <div></div>
                <div><p class="transition-2s">Default</p></div>
            </button>
            <button type="submit" name="submit" value="Light">
                <div></div>
                <div></div>
                <div><p class="transition-2s">Light</p></div>
            </button>
            <button type="submit" name="submit" value="Dark">
                <div></div>
                <div></div>
                <div><p class="transition-2s">Dark</p></div>
            </button>
            <button type="submit" name="submit" value="Agua">
                <div></div>
                <div></div>
                <div><p class="transition-2s">Agua</p></div>
            </button>
            <button type="submit" name="submit" value="Sunrise">
                <div></div>
                <div></div>
                <div><p class="transition-2s">Sunrise</p></div>
            </button>
            <button type="submit" name="submit" value="Berry">
                <div></div>
                <div></div>
                <div><p class="transition-2s">Berry</p></div>
            </button>
            <button type="submit" name="submit" value="Pastel">
                <div></div>
                <div></div>
                <div><p class="transition-2s">Pastel</p></div>
            </button>
        </form>
    </div>
}

Etch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Page Title -->
    <title>Etch | @ViewData["Title"]</title>

    <!-- Character Encoding validation -->
    <meta charset="utf-8" />
    <!-- Viewport Width -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Compatability -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- About Etch -->
    <meta name="description" content="A free study planner for students, teachers and lecturers designed to
                  put you in control of your study life. Making it easier than ever to manage online." />
    <!-- Search Engine Queries -->
    <meta name="keywords" content="Etch, study planner, study, planner, student, students, teacher, teachers,
                  lecturer, lecturers, online, website, application" />
    <!-- Index Website -->
    <meta name="robots" content="index, follow" />

    <!-- Icon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicons/favicon-16x16.png">
    <link rel="manifest" href="~/favicons/site.webmanifest">
    <link rel="mask-icon" href="~/favicons/safari-pinned-tab.svg" color="#0c2035">
    <meta name="msapplication-TileColor" content="#0c2035">
    <meta name="theme-color" content="#0c2035">

    <environment include="Development">
        <!-- Get Normalize CSS -->
        <link rel="stylesheet" href="~/assets/styles/normalize.min.css" />
        <!-- Get Master CSS -->
        <link rel="stylesheet" href="~/assets/styles/master.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/assets/styles/site.min.css" />
    </environment>
    @RenderSection("styles", required: false)
</head>

<body>
    <div class="background-theme" style="background: @await Component.InvokeAsync("Theme") !important"></div>
   
    <!-- Header -->
    <header>
        @await Html.PartialAsync("_HeaderPartial")
    </header>

    <!-- Page Content -->
    <main class="transition-4s">
        @RenderBody()
    </main>

    <!-- Footer -->
    <footer>
        <!-- Copyright Information -->
        <p class="copyright font-size-small">2018 &copy; <a asp-area="" asp-controller="Home" asp-action="Index" class="link">Etch</a>. All Rights Reserved.</p>
    </footer>

    <environment include="Development">
        <!-- Get JQuery -->
        <script src="~/assets/scripts/jquery-3.2.1.min.js"></script>
        <!-- Get Master JS -->
        <script src="~/assets/scripts/master.js"></script>
    </environment>
    <environment exclude="Development">
        <!-- Get Minified Site JS -->
        <script src="~/assets/scipts/site.min.js"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>

Etch/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model)) {
    <div class="message">@Model</div>
}

Etch/Views/Shared/_Theme.cshtml
@model Etch.Models.ThemeModel;
@{ string gradient;
    switch (Model.Theme) {
        case ApplicationUser.Themes.Default:
            gradient = "linear-gradient(#cf69b9, #125aa5)";
            break;

        case ApplicationUser.Themes.Light:
            gradient = "linear-gradient(#ccc, #ccc)";
            break;

        case ApplicationUser.Themes.Dark:
            gradient = "linear-gradient(#333, #333)";
            break;

        case ApplicationUser.Themes.Agua:
            gradient = "linear-gradient(#1fba5f, #158ba0)";
            break;

        case ApplicationUser.Themes.Sunrise:
            gradient = "linear-gradient(#bf871c, #d74343)";
            break;

        case ApplicationUser.Themes.Berry:
            gradient = "linear-gradient(#be464c, #773395)";
            break;

        case ApplicationUser.Themes.Pastel:
            gradient = "linear-gradient(#f5aee2, #33a38a)";
            break;

        default:
            gradient = "linear-gradient(#cf69b9, #125aa5)";
            break;
    }
}
@gradient